---
name: Aleksei Mikhalev
job: QA Engineer
level: junior
email: tsydenov.al@yandex.ru
deskription: | 
hexlet school student
skills:
- функциональное тестирование
- кроссбраузерное тестирование
- базовые методы ручного тестирования
- работа с системами мобильных и веб приложений
